name: Release on Commit

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get commit SHA
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.sha }}
        release_name: Release ${{ steps.vars.outputs.sha }}
        body: "Automated release based on commit ${{ steps.vars.outputs.sha }} \ **See Changelog:** [`...main`](https://github.com/PalmarHealer/wochenplan/commits/main/)"
        draft: false
        prerelease: false
