name: Create release for latest version

on:
  workflow_dispatch:  # Manual trigger via GitHub UI
    inputs:
      should_run:
        description: 'This Release has not been genrated jet?'
        required: true
        type: boolean
jobs:
  create_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.should_run == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the latest code from the main branch

    - name: Get latest version from JSON
      id: get_version
      run: |
        LATEST_VERSION=$(jq -r '.versions[-1].version' dependencies/versioner.json)
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.LATEST_VERSION }}
        name: Release ${{ env.LATEST_VERSION }}
        body: "Manual release based on version ${{ env.LATEST_VERSION }} in versioner.json. **See Changelog:** [here](https://github.com/PalmarHealer/wochenplan/commits/main/)"
        draft: false
        prerelease: false
